infrastructure:
  db:
    dsn: postgresql+asyncpg://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
    pool_size: 15
    pool_recycle: 1800
  kafka:
    bootstrap_servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    topic_produce: ${KAFKA_PRODUCE_TOPIC:orders}
    topic_consume_payments: ${KAFKA_CONSUME_TOPIC_PAYMENTS:payments}
    topic_consume_shipments: ${KAFKA_CONSUME_TOPIC_SHIPMENTS:shipments}
    topic_consume_cancels: ${KAFKA_CONSUME_TOPIC_CANCELS:cancels}